name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check
      run:  pwd && ls -la && ls -la libs && ls -la libs/libft
    - name: make
      run: make
